load("//tools:hdl.bzl", "vhdl_unit")
load("//tools:yosys.bzl", "ice40_bitstream")

vhdl_unit(
    name = "metro_ignition_top",
    srcs = glob(["*.vhd"]),
    deps = [
        "//hdl/ip/vhd/ignition/target:ignition_target_common",
        "//hdl/ip/vhd/ignition/target:ignition_io",
        "//hdl/ip/vhd/synchronizers:meta_sync",
    ],
    standard = "2008",
)

ice40_bitstream(
    name = "metro_ignition",
    top_entity_name = "metro_ignition_top",
    top = ":metro_ignition_top",
    family = "hx8k",
    package = "bg121",
    pinmap = "metro_ignition.pcf",
)
