load("//tools:hdl.bzl", "vhdl_unit")

vhdl_unit(
    name = "calc_pkg",
    srcs = ["calc_pkg.vhd",],
    visibility = ['PUBLIC'],
)

vhdl_unit(
    name = "time_pkg",
    srcs = ["time_pkg.vhd",],
    visibility = ['PUBLIC'],
)

vhdl_unit(
    name = "transforms_pkg",
    srcs = ["transforms_pkg.vhd",],
    visibility = ['PUBLIC'],
)