cobble:
  - .github/**/*
  - 'tools/site_cobble/**/*'
  - 'vnd/**/*'
  - 'hdl/ip/bsv/**/*'
  - 'hdl/projects/ecp5_evn/**/*'
  - 'hdl/projects/gimlet/**/*'
  - 'hdl/projects/icestick/**/*'
  - 'hdl/projects/ignitionlet/**/*'
  - 'hdl/projects/minibar/**/*'
  - 'hdl/projects/psc/**/*'
  - 'hdl/projects/sidecar/**/*'
  - 'hdl/projects/ulx3s/**/*'
            
buck2:
  - .github/**/*
  - 'vnd/xpm/**/*'
  - 'prelude/**/*'
  - 'toolchains/**/*'
  - 'hdl/ip/toolchains/**/*'
  - 'tools/**/*'
  - 'hdl/ip/vhd/**/*'

grapefruit:
  - 'hdl/projects/grapefruit/**/*'

cosmo_hp:
  - 'hdl/projects/cosmo_hp/**/*'

cosmo_seq:
  - 'hdl/projects/cosmo_seq/**/*'