load("//tools:hdl.bzl", "vhdl_unit")
load("//tools:rdl.bzl", "rdl_file")

vhdl_unit(
    name = "xpm",
    library = "xpm",
    srcs = glob(["xpm_vhdl/**/*.vhd"], exclude = ["**/simulation/*.vhd"]),
    visibility = ['PUBLIC'],
)