load("//tools:hdl.bzl", "third_party", "sim_only_model")

third_party(
        name = "xpm",
        library = "xpm",
        is_synth = False,
        srcs = glob(["xpm_vhdl/**/*.vhd"], exclude = ["**/simulation/*.vhd"]),
        visibility = ['PUBLIC'],
)