standard = "2019"

[libraries.xpm]
files = [
    "vnd/xpm/xpm_vhdl/src/xpm/xpm_VCOMP.vhd",
    "vnd/xpm/xpm_vhdl/src/xpm/xpm_cdc/hdl/xpm_cdc_array_single.vhd",
    "vnd/xpm/xpm_vhdl/src/xpm/xpm_cdc/hdl/xpm_cdc_async_rst.vhd",
    "vnd/xpm/xpm_vhdl/src/xpm/xpm_cdc/hdl/xpm_cdc_gray.vhd",
    "vnd/xpm/xpm_vhdl/src/xpm/xpm_cdc/hdl/xpm_cdc_handshake.vhd",
    "vnd/xpm/xpm_vhdl/src/xpm/xpm_cdc/hdl/xpm_cdc_low_latency_handshake.vhd",
    "vnd/xpm/xpm_vhdl/src/xpm/xpm_cdc/hdl/xpm_cdc_pulse.vhd",
    "vnd/xpm/xpm_vhdl/src/xpm/xpm_cdc/hdl/xpm_cdc_single.vhd",
    "vnd/xpm/xpm_vhdl/src/xpm/xpm_cdc/hdl/xpm_cdc_sync_rst.vhd",
    "vnd/xpm/xpm_vhdl/src/xpm/xpm_fifo/hdl/xpm_counter_updn.vhd",
    "vnd/xpm/xpm_vhdl/src/xpm/xpm_fifo/hdl/xpm_fifo_async.vhd",
    "vnd/xpm/xpm_vhdl/src/xpm/xpm_fifo/hdl/xpm_fifo_axi_reg_slice.vhd",
    "vnd/xpm/xpm_vhdl/src/xpm/xpm_fifo/hdl/xpm_fifo_axif.vhd",
    "vnd/xpm/xpm_vhdl/src/xpm/xpm_fifo/hdl/xpm_fifo_axil.vhd",
    "vnd/xpm/xpm_vhdl/src/xpm/xpm_fifo/hdl/xpm_fifo_axis.vhd",
    "vnd/xpm/xpm_vhdl/src/xpm/xpm_fifo/hdl/xpm_fifo_base.vhd",
    "vnd/xpm/xpm_vhdl/src/xpm/xpm_fifo/hdl/xpm_fifo_reg_bit.vhd",
    "vnd/xpm/xpm_vhdl/src/xpm/xpm_fifo/hdl/xpm_fifo_reg_vec.vhd",
    "vnd/xpm/xpm_vhdl/src/xpm/xpm_fifo/hdl/xpm_fifo_rst.vhd",
    "vnd/xpm/xpm_vhdl/src/xpm/xpm_fifo/hdl/xpm_fifo_sync.vhd",
    "vnd/xpm/xpm_vhdl/src/xpm/xpm_fifo/hdl/xpm_reg_pipe_bit.vhd",
    "vnd/xpm/xpm_vhdl/src/xpm/xpm_memory/hdl/xpm_memory_base.vhd",
    "vnd/xpm/xpm_vhdl/src/xpm/xpm_memory/hdl/xpm_memory_dpdistram.vhd",
    "vnd/xpm/xpm_vhdl/src/xpm/xpm_memory/hdl/xpm_memory_dprom.vhd",
    "vnd/xpm/xpm_vhdl/src/xpm/xpm_memory/hdl/xpm_memory_sdpram.vhd",
    "vnd/xpm/xpm_vhdl/src/xpm/xpm_memory/hdl/xpm_memory_spram.vhd",
    "vnd/xpm/xpm_vhdl/src/xpm/xpm_memory/hdl/xpm_memory_sprom.vhd",
    "vnd/xpm/xpm_vhdl/src/xpm/xpm_memory/hdl/xpm_memory_tdpram.vhd",
]

[libraries.worklib]
files = [
    "hdl/projects/grapefruit/grapefruit_top.vhd",
    "hdl/projects/gimlet/vhdl_test/leds.vhd",
    "hdl/ip/vhd/vunit_components/gpio_msg_pkg.vhd",
    "hdl/ip/vhd/vunit_components/sim_gpio.vhd",
    "hdl/ip/vhd/utilities/calc_pkg.vhd",
    "hdl/ip/vhd/utilities/time_pkg.vhd",
    "hdl/ip/vhd/utilities/transforms_pkg.vhd",
    "hdl/ip/vhd/utilities/sims/utilities_tb.vhd",
    "hdl/ip/vhd/synchronizers/tacd.vhd",
    "hdl/ip/vhd/synchronizers/async_reset_bridge.vhd",
    "hdl/ip/vhd/synchronizers/meta_sync.vhd",
    "hdl/ip/vhd/synchronizers/bacd.vhd",
    "hdl/ip/vhd/synchronizers/sims/synchronizers_tb.vhd",
    "hdl/ip/vhd/synchronizers/sims/synchronizers_th.vhd",
    "hdl/ip/vhd/axi_blocks/axil_common_pkg.vhd",
    "hdl/ip/vhd/axi_blocks/axilite_if_pkg.vhd",
    "hdl/ip/vhd/axi_blocks/axil_interconnect.vhd",
    "hdl/ip/vhd/fifos/dcfifo_xpm.vhd",
    "hdl/ip/vhd/spi_nor_controller/mixed_width_adaptor.vhd",
    "hdl/ip/vhd/spi_nor_controller/spi_clk_gen.vhd",
    "hdl/ip/vhd/spi_nor_controller/spi_link.vhd",
    "hdl/ip/vhd/spi_nor_controller/spi_nor_pkg.vhd",
    "hdl/ip/vhd/spi_nor_controller/spi_nor_regs.vhd",
    "hdl/ip/vhd/spi_nor_controller/spi_nor_top.vhd",
    "hdl/ip/vhd/spi_nor_controller/spi_txn_mgr.vhd",
    "hdl/ip/vhd/spi_nor_controller/sims/spi_nor_tb.vhd",
    "hdl/ip/vhd/spi_nor_controller/sims/spi_nor_tb_pkg.vhd",
    "hdl/ip/vhd/spi_nor_controller/sims/spi_nor_th.vhd",
    "hdl/ip/vhd/memories/dual_clock_simple_dpr.vhd",
    "hdl/ip/vhd/memories/sims/memories_sim_pkg.vhd",
    "hdl/ip/vhd/memories/sims/memories_tb.vhd",
    "hdl/ip/vhd/memories/sims/memories_th.vhd",
    "hdl/ip/vhd/fmc_if/stm32h7_fmc_target.vhd",
    "hdl/ip/vhd/fmc_if/stm32h7_fmc_target_pkg.vhd",
    "hdl/ip/vhd/fmc_if/model/stm32h7_fmc_model.vhd",
    "hdl/ip/vhd/fmc_if/model/stm32h7_fmc_sim_pkg.vhd",
    "hdl/ip/vhd/fmc_if/sims/fmc_tb.vhd",
    "hdl/ip/vhd/fmc_if/sims/fmc_tb_pkg.vhd",
    "hdl/ip/vhd/fmc_if/sims/fmc_th.vhd",
    "hdl/ip/vhd/fifos/sims/fifos_sim_pkg.vhd",
    "hdl/ip/vhd/fifos/sims/fifos_tb.vhd",
    "hdl/ip/vhd/fifos/sims/fifos_th.vhd",
    "hdl/ip/vhd/arb_mux_demux/arbiter.vhd",
    "hdl/ip/vhd/arb_mux_demux/arbiter_pkg.vhd",
    "hdl/ip/vhd/arb_mux_demux/sims/arbiter_sim_pkg.vhd",
    "hdl/ip/vhd/arb_mux_demux/sims/arbiter_tb.vhd",
    "hdl/ip/vhd/arb_mux_demux/sims/arbiter_th.vhd",
    "hdl/ip/vhd/fifos/dcfifo_mixed_xpm.vhd",
    "buck-out/v2/gen/root/904931f735703749/hdl/ip/vhd/spi_nor_controller/__spi_nor_rdl__/spi_nor_regs_pkg.vhd",
]
