load("@prelude//toolchains:python.bzl", "system_python_bootstrap_toolchain", "system_python_toolchain")
load("@prelude//toolchains:cxx.bzl", "system_cxx_toolchain")
load("@prelude//toolchains:remote_test_execution.bzl", "remote_test_execution_toolchain")
load("@prelude//toolchains:genrule.bzl", "system_genrule_toolchain")

load("vivado_toolchain.bzl", "vivado_toolchain")
load("vsg_toolchain.bzl", "vsg_toolchain")
load("bsv_toolchain.bzl", "bsv_toolchain")

load("yosys_toolchain.bzl", "icepack_toolchain", "nextpnr_ice40_toolchain", "nextpnr_ecp5_toolchain", "ecppack_toolchain", "icebram_toolchain", "ecpbram_toolchain", "yosys_toolchain")

system_genrule_toolchain(
    name = "genrule",
    visibility = ["PUBLIC"],
)

system_cxx_toolchain(
    name = "cxx",
    visibility = ["PUBLIC"],
)

system_python_toolchain(
    name = "python",
    visibility = ["PUBLIC"],
)

system_python_bootstrap_toolchain(
    name = "python_bootstrap",
    visibility = ["PUBLIC"],
)

vivado_toolchain(
    name = "vivado",
    visibility = ["PUBLIC"],
)

vsg_toolchain(
    name = "vsg",
    visibility = ["PUBLIC"],
)

bsv_toolchain(
    name = "bsv",
    visibility = ["PUBLIC"],
)

yosys_toolchain(
    name = "yosys",
    visibility = ["PUBLIC"],
)

icepack_toolchain(
    name = "icepack",
    visibility = ["PUBLIC"],
)

nextpnr_ice40_toolchain(
    name = "nextpnr-ice40",
    visibility = ["PUBLIC"],
)

nextpnr_ecp5_toolchain(
    name = "nextpnr-ecp5",
    visibility = ["PUBLIC"],
)

ecppack_toolchain(
    name = "ecppack",
    visibility = ["PUBLIC"],
)

icebram_toolchain(
    name = "icebram",
    visibility = ["PUBLIC"],
)

ecpbram_toolchain(
    name = "ecpbram",
    visibility = ["PUBLIC"],
)

remote_test_execution_toolchain(
    name = "remote_test_execution",
    visibility = ["PUBLIC"],
)