load("@prelude//toolchains:python.bzl", "system_python_bootstrap_toolchain", "system_python_toolchain")
load("@prelude//toolchains:cxx.bzl", "system_cxx_toolchain")
load("@prelude//toolchains:remote_test_execution.bzl", "remote_test_execution_toolchain")

load("vivado_toolchain.bzl", "vivado_toolchain")
load("vsg_toolchain.bzl", "vsg_toolchain")

load("yosys_toolchain.bzl", "icepack_toolchain", "nextpnr_ice40_toolchain")

system_cxx_toolchain(
    name = "cxx",
    visibility = ["PUBLIC"],
)

system_python_toolchain(
    name = "python",
    visibility = ["PUBLIC"],
)

system_python_bootstrap_toolchain(
    name = "python_bootstrap",
    visibility = ["PUBLIC"],
)

vivado_toolchain(
    name = "vivado",
    visibility = ["PUBLIC"],
)

vsg_toolchain(
    name = "vsg",
    visibility = ["PUBLIC"],
)

icepack_toolchain(
    name = "icepack",
    visibility = ["PUBLIC"],
)

nextpnr_ice40_toolchain(
    name = "nextpnr-ice40",
    visibility = ["PUBLIC"],
)

remote_test_execution_toolchain(
    name = "remote_test_execution",
    visibility = ["PUBLIC"],
)