load("//tools:hdl.bzl", "vhdl_unit")

vhdl_unit(
    name = "crc8atm_8wide",
    srcs = ["crc8atm_8wide.vhd"],
    visibility = ['PUBLIC']
)

vhdl_unit(
    name = "crc8astar_8wide",
    srcs = ["crc8astar_8wide.vhd"],
    visibility = ['PUBLIC']
)