load("//tools:hdl.bzl", "vhdl_unit")

vhdl_unit(
    name = "arbiter",
    srcs = [
        "arbiter.vhd",
        "arbiter_pkg.vhd"
    ],
    visibility = ['PUBLIC'],
)

vhdl_unit(
    name = "arbiter_tb",
    is_tb = True,
    srcs = glob(["sims/*.vhd"]),
    deps = [
        ":arbiter",
        "//hdl/ip/vhd/vunit_components:sim_gpio"
    ],
    visibility = ['PUBLIC'],
)