load("//tools:hdl.bzl", "vhdl_unit")

vhdl_unit(
    name = "axilite_common_pkgs",
    srcs = glob(["*pkg.vhd"]),
    standard = "2019",
    visibility = ['PUBLIC'],
)

vhdl_unit(
    name = "axil_interconnect",
    srcs = glob(["axil_interconnect.vhd"]),
    deps = [
        ":axilite_common_pkgs",
    ],
    visibility = ['PUBLIC'],
)
