load("//tools:hdl.bzl", "vhdl_unit")

vhdl_unit(
    name = "uart_rx",
    srcs = ["uart_rx.vhd",],
)

vhdl_unit(
    name = "uart_tx",
    srcs = ["uart_tx.vhd"],
)

vhdl_unit(
    name = "tb_uart_rx",
    srcs = ["tb_uart_rx.vhd"],
    deps = [":uart_rx"],
    is_tb = True
)

vhdl_unit(
    name = "tb_uart_tx",
    srcs = ["tb_uart_tx.vhd"],
    deps = [":uart_tx"],
    is_tb = True
)