load("//tools:hdl.bzl", "vhdl_unit", "vunit_sim")
load("//tools:rdl.bzl", "rdl_file")

vhdl_unit(
    name = "sp5_hotplug_subsystem",
    srcs = ["sp5_hotplug_subsystem.vhd",
    ],
    deps = [
        "//hdl/ip/vhd/synchronizers:meta_sync",
        "//hdl/ip/vhd/i2c/io_expanders/PCA9506ish:pca9506_top",
    ],
    standard = "2019",
    visibility = ["PUBLIC"],
)