load("//tools:hdl.bzl", "vhdl_unit", "vunit_sim")
load("//tools:rdl.bzl", "rdl_file")

vhdl_unit(
    name = "perst_oneshot",
    srcs = ["perst_oneshot.vhd"],
    deps = [
        "//hdl/ip/vhd/common:calc_pkg",
    ],
    visibility = ["PUBLIC"],
)

vhdl_unit(
    name = "sp5_hotplug_subsystem",
    srcs = ["sp5_hotplug_subsystem.vhd",
    ],
    deps = [
        ":perst_oneshot",
        "//hdl/ip/vhd/common:time_pkg",
        "//hdl/ip/vhd/synchronizers:meta_sync",
        "//hdl/ip/vhd/axi_blocks:axist_if_2k19_pkg",
        "//hdl/ip/vhd/i2c/io_expanders/PCA9506ish:pca9506_top",
    ],
    standard = "2019",
    visibility = ["PUBLIC"],
)
vunit_sim(
    name = "sp5_hotplug_tb",
    srcs = glob(["sims/*.vhd"]),
    deps = [
        ":sp5_hotplug_subsystem",
        "//hdl/ip/vhd/i2c/io_expanders/PCA9506ish:pca9506_sim_pkg",
        "//hdl/ip/vhd/vunit_components:i2c_controller_vc",
        "//hdl/ip/vhd/axi_blocks:axilite_if_2k19",
    ],
    visibility = ["PUBLIC"],
    standard = "2019",
)
