load("//tools:hdl.bzl", "vhdl_unit")

vhdl_unit(
    name = "lfsr8_pkg",
    srcs = ["lfsr8_pkg.vhd"],
    visibility = ['PUBLIC'],
)

vhdl_unit(
    name = "scrambler_lfsr8",
    srcs = ["scrambler_lfsr8.vhd"],
    deps = [":lfsr8_pkg"],
    visibility = ['PUBLIC'],
)

vhdl_unit(
    name = "lfsr_tb",
    is_tb = True,
    srcs = glob(["sims/*.vhd"]),
    deps = [":scrambler_lfsr8"],
    visibility = ['PUBLIC'],
)
