load("//tools:bsv.bzl", "bsv_bluesim_tests")
load("//tools:bsv.bzl", "bsv_library")
load("//tools:rdl.bzl", "rdl_file")

# rdl_file
# Note: Buck2 RDL rule enforces strict naming convention
# BSV outputs use "Regs" suffix, VHDL uses "_pkg" suffix
rdl_file(
    visibility = ["PUBLIC"],
    name = "I2CCore_rdl",
    outputs = [
        "I2CCoreRegs.bsv",
        "I2CCore.html",
        "I2CCore.json",
    ],
    src = "I2CCore.rdl",
)

# bsv_library
bsv_library(
    visibility = ["PUBLIC"],
    name = "I2CCoreRegs",
    srcs = [":I2CCore_rdl"],
    deps = [
        "//hdl/ip/bsv:RegCommon",
    ],
)

# bsv_library
bsv_library(
    visibility = ["PUBLIC"],
    name = "I2CCommon",
    srcs = ["I2CCommon.bsv"],
    deps = ["//hdl/ip/bsv:Bidirection"],
)

# bsv_library
bsv_library(
    visibility = ["PUBLIC"],
    name = "I2CBitController",
    srcs = ["I2CBitController.bsv"],
    deps = [
        ":I2CCommon",
        "//hdl/ip/bsv:Strobe",
    ],
)

# bsv_library
bsv_library(
    visibility = ["PUBLIC"],
    name = "I2CCore",
    srcs = ["I2CCore.bsv"],
    deps = [
        ":I2CCommon",
        ":I2CBitController",
    ],
)

# bsv_library
bsv_library(
    visibility = ["PUBLIC"],
    name = "I2CPeripheralModel",
    srcs = ["test/I2CPeripheralModel.bsv"],
    deps = [
        ":I2CCommon",
        "//hdl/ip/bsv:Countdown",
        "//hdl/ip/bsv:Strobe",
    ],
)

# bsv_bluesim_tests
bsv_bluesim_tests(
    name = "I2CBitControllerTests",
    suite = "test/I2CBitControllerTests.bsv",
    modules = [
        "mkI2CBitControlOneByteWriteTest",
        "mkI2CBitControlOneByteReadTest",
        "mkI2CBitControlSequentialWriteTest",
        "mkI2CBitControlSequentialReadTest",
        "mkI2CBitControlRandomReadTest",
        "mkI2CBitControlSclStretchTest",
        "mkI2CBitControlSclStretchTimeoutTest",
    ],
    deps = [
        ":I2CBitController",
        ":I2CCommon",
        ":I2CPeripheralModel",
    ],
)

# bsv_bluesim_tests
bsv_bluesim_tests(
    name = "I2CCoreTests",
    suite = "test/I2CCoreTests.bsv",
    modules = [
        "mkI2CCoreOneByteWriteTest",
        "mkI2CCoreOneByteReadTest",
        "mkI2CCoreSequentialWriteTest",
        "mkI2CCoreSequentialReadTest",
        "mkI2CCoreRandomReadTest",
        "mkI2CCoreSclStretchTest",
        "mkI2CCoreSclStretchTimeoutTest",
        "mkI2CCoreAbortTest",
    ],
    deps = [
        ":I2CBitController",
        ":I2CCommon",
        ":I2CCore",
        ":I2CPeripheralModel",
    ],
)
