load("//tools:hdl.bzl", "vhdl_unit")
load("//tools:yosys.bzl", "ice40_bitstream")

vhdl_unit(
    name = "leds",
    srcs = glob(["*.vhd"]),
    standard = "2008",
)

ice40_bitstream(
    name="leds_top",
    top_entity_name="leds",
    top= ":leds",
    package="hx1k",
    pinmap="pinmap.pcf"
)