-- This Source Code Form is subject to the terms of the Mozilla Public
-- License, v. 2.0. If a copy of the MPL was not distributed with this
-- file, You can obtain one at https://mozilla.org/MPL/2.0/.
--
-- GTY transceiver wrapper for the SGMII line side. Adapts the Vivado GT wizard
-- core (gtwizard_sgmii, generated by xilinx_ip_gen/gtwizard_sgmii_ip.tcl) to the
-- clean interface the soft SGMII PCS expects: comma-aligned 10-bit code groups
-- in a single 125 MHz user-clock domain.
--
--   freerun_clk   : always-on 62.5 MHz clock derived from the 125 MHz GT refclk
--                   (refclk / 2 via the IBUFDS_GTE4 ODIV2 + BUFG_GT); feeds the
--                   GT reset FSM and the project MMCM. The XEM8320 has no fabric
--                   oscillator, so the GT refclk is the only always-on source.
--   usrclk        : forwarded 125 MHz user clock (drives the bridge)
--   rx_code       : aligned 10-bit code group from the line (one per usrclk)
--   rx_code_valid : asserted once the GT is up and byte-aligned
--   tx_code       : 10-bit code group to transmit (from the PCS)
--   gt_ready      : GT tx+rx reset done and RX byte-aligned
--
-- The GT does no 8b10b (bypassed); the soft PCS owns 8b10b and ordered sets.
-- The GT's RX buffer + clock correction (on the K28.5 idle sequence) keep rx in
-- the tx user-clock domain, so the PCS sees a single clock.

library ieee;
    use ieee.std_logic_1164.all;

entity sgmii_gt is
    port (
        -- GT reference clock (differential); onboard 125 MHz, MGTREFCLK0_226
        mgtrefclk_p : in    std_logic;
        mgtrefclk_n : in    std_logic;

        -- serial line side
        gt_rxp : in    std_logic;
        gt_rxn : in    std_logic;
        gt_txp : out   std_logic;
        gt_txn : out   std_logic;

        reset : in    std_logic;

        -- always-on clock derived from the refclk (for the project MMCM)
        freerun_clk : out   std_logic;

        -- user-domain interface to the soft PCS
        usrclk        : out   std_logic;
        rx_code       : out   std_logic_vector(9 downto 0);
        rx_code_valid : out   std_logic;
        tx_code       : in    std_logic_vector(9 downto 0);

        gt_ready : out   std_logic
    );
end entity;

architecture rtl of sgmii_gt is

    -- GT reference-clock input buffer and global clock buffer (Vivado binds by
    -- name; declared locally so the analyzer/LSP is happy).
    component ibufds_gte4 is
        generic (
            refclk_en_tx_path  : bit                          := '0';
            refclk_hrow_ck_sel : std_logic_vector(1 downto 0) := "00";
            refclk_icntl_rx    : std_logic_vector(1 downto 0) := "00"
        );
        port (
            o     : out   std_ulogic;
            odiv2 : out   std_ulogic;
            ceb   : in    std_ulogic;
            i     : in    std_ulogic;
            ib    : in    std_ulogic
        );
    end component;

    component bufg_gt is
        port (
            o       : out   std_ulogic;
            ce      : in    std_ulogic;
            cemask  : in    std_ulogic;
            clr     : in    std_ulogic;
            clrmask : in    std_ulogic;
            div     : in    std_logic_vector(2 downto 0);
            i       : in    std_ulogic
        );
    end component;

    signal gtrefclk    : std_logic;
    signal gtrefclk_d2 : std_logic;
    signal freerun_i   : std_logic;

    signal tx_done    : std_logic;
    signal rx_done    : std_logic;
    signal rx_aligned : std_logic;
    signal usrclk_i   : std_logic;

begin

    usrclk      <= usrclk_i;
    freerun_clk <= freerun_i;
    gt_ready    <= tx_done and rx_done and rx_aligned;

    -- code groups are valid once the link is fully up and aligned
    rx_code_valid <= tx_done and rx_done and rx_aligned;

    -- refclk input buffer: O drives the GT, ODIV2 (refclk / 2) the free-run path
    refclk_ibuf: component ibufds_gte4
        port map (
            o     => gtrefclk,
            odiv2 => gtrefclk_d2,
            ceb   => '0',
            i     => mgtrefclk_p,
            ib    => mgtrefclk_n
        );

    freerun_bufg: component bufg_gt
        port map (
            o       => freerun_i,
            ce      => '1',
            cemask  => '0',
            clr     => '0',
            clrmask => '0',
            div     => "000",
            i       => gtrefclk_d2
        );

    gt_i: entity work.gtwizard_sgmii
        port map (
            gtrefclk00_in => gtrefclk,

            gtyrxp_in  => gt_rxp,
            gtyrxn_in  => gt_rxn,
            gtytxp_out => gt_txp,
            gtytxn_out => gt_txn,

            gtwiz_reset_clk_freerun_in => freerun_i,
            gtwiz_reset_all_in         => reset,
            gtwiz_reset_tx_done_out    => tx_done,
            gtwiz_reset_rx_done_out    => rx_done,
            rxbyteisaligned_out        => rx_aligned,

            gtwiz_userclk_tx_usrclk2_out => usrclk_i,
            gtwiz_userclk_rx_usrclk2_out => open,  -- same domain (RX buffer)

            gtwiz_userdata_tx_in  => tx_code,
            gtwiz_userdata_rx_out => rx_code
        );

end architecture;
