load("//tools:hdl.bzl", "vhdl_unit", "vunit_sim")
load("//tools:rdl.bzl", "rdl_file")

vhdl_unit(
    name = "sp_i2c_subsystem",
    srcs = ["sp_i2c_subsystem.vhd",
    ],
    deps = [
        "//hdl/ip/vhd/axi_blocks:axist_if_2k19_pkg",
        "//hdl/ip/vhd/axi_blocks:axil_interconnect",
        "//hdl/ip/vhd/i2c/muxes/PCA9545ish:pca9545ish_top",
        "//hdl/ip/vhd/i2c/target:i2c_phy_consolidator",
    ],
    standard = "2019",
    visibility = ["PUBLIC"],
)