create_debug_core u_ila_0 ila
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
connect_debug_port u_ila_0/clk [get_nets [list board_support_inst/pll/inst/clk_125m ]]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {stm32h7_fmc_target_inst/axi_addr[0]} {stm32h7_fmc_target_inst/axi_addr[1]} {stm32h7_fmc_target_inst/axi_addr[2]} {stm32h7_fmc_target_inst/axi_addr[3]} {stm32h7_fmc_target_inst/axi_addr[4]} {stm32h7_fmc_target_inst/axi_addr[5]} {stm32h7_fmc_target_inst/axi_addr[6]} {stm32h7_fmc_target_inst/axi_addr[7]} {stm32h7_fmc_target_inst/axi_addr[8]} {stm32h7_fmc_target_inst/axi_addr[9]} {stm32h7_fmc_target_inst/axi_addr[10]} {stm32h7_fmc_target_inst/axi_addr[11]} {stm32h7_fmc_target_inst/axi_addr[12]} {stm32h7_fmc_target_inst/axi_addr[13]} {stm32h7_fmc_target_inst/axi_addr[14]} {stm32h7_fmc_target_inst/axi_addr[15]} {stm32h7_fmc_target_inst/axi_addr[16]} {stm32h7_fmc_target_inst/axi_addr[17]} {stm32h7_fmc_target_inst/axi_addr[18]} {stm32h7_fmc_target_inst/axi_addr[19]} {stm32h7_fmc_target_inst/axi_addr[20]} {stm32h7_fmc_target_inst/axi_addr[21]} {stm32h7_fmc_target_inst/axi_addr[22]} {stm32h7_fmc_target_inst/axi_addr[23]} {stm32h7_fmc_target_inst/axi_addr[24]} {stm32h7_fmc_target_inst/axi_addr[25]} {stm32h7_fmc_target_inst/axi_addr[26]} {stm32h7_fmc_target_inst/axi_addr[27]} {stm32h7_fmc_target_inst/axi_addr[28]} {stm32h7_fmc_target_inst/axi_addr[29]} {stm32h7_fmc_target_inst/axi_addr[30]} {stm32h7_fmc_target_inst/axi_addr[31]} ]]
create_debug_port u_ila_0 probe
set_property port_width 3 [get_debug_ports u_ila_0/probe1]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {stm32h7_fmc_target_inst/axi_state[0]} {stm32h7_fmc_target_inst/axi_state[1]} {stm32h7_fmc_target_inst/axi_state[2]} ]]