python_binary(
    name = 'vivado_ip',
    main = 'vivado_ip.py',
    deps = [':vivado_ip_lib'],
    visibility = ["PUBLIC"],
)

python_library(
    name = 'vivado_ip_lib',
    srcs = glob(["*.py"]),
    base_module = "vivado_ip",
    resources = glob(["templates/*.jinja2"])
)