python_binary(
    name = 'multitool',
    main = 'multitool_cli.py',
    deps = [':multitool_lib'],
    visibility = ["PUBLIC"],
)

python_library(
    name = 'multitool_lib',
    srcs = glob(["*.py"]),
    base_module = "multitool",
    resources = glob(["templates/*.jinja2"])
)