python_binary(
    name = 'vunit_gen',
    main = 'vunit_gen_cli.py',
    deps = [':vunit_gen_lib'],
    visibility = ["PUBLIC"],
)

python_library(
    name = 'vunit_gen_lib',
    srcs = glob(["*.py"]),
    base_module = "vunit_gen",
    resources = glob(["templates/*.jinja2"])
)