python_binary(
    name = 'rdl_cli',
    main = 'rdl_cli.py',
    deps = [':rdl_lib'],
    visibility = ["PUBLIC"],
)

python_library(
    name = 'rdl_lib',
    base_module = "rdl_pkg",
    srcs = glob(["*.py"]),
    resources = glob(["templates/*.jinja2"]),
)