load("//tools:hdl.bzl", "vhdl_unit", "vunit_sim")
load("//tools:rdl.bzl", "rdl_file")

vhdl_unit(
    name = "sp5_uart_subsystem",
    srcs = glob(["*.vhd"]),
    deps = [
        "//hdl/ip/vhd/uart:axi_fifo_uart",
        "//hdl/ip/vhd/axi_blocks:axist_if_2k19_pkg",
    ],
    standard = "2019",
    visibility = ["PUBLIC"],
)