[cosmo-hp]
job_name = "cosmo-hp-image"
hubris_path = "drv/cosmo-seq-server/cosmo-hp"
builder = "buck2"
toolchain = "yosys"

[cosmo-ignition]
job_name = "cosmo-ignition-image"
builder = "buck2"
toolchain = "yosys"

[cosmo-ignition-r1-only]
job_name = "cosmo-ignition-r1-only-image"
builder = "buck2"
toolchain = "yosys"

[cosmo-seq]
job_name = "cosmo-seq-image"
hubris_path = "drv/spartan7-loader/cosmo-seq"
builder = "buck2"
toolchain = "vivado"

[grapefruit]
job_name = "gfruit-image"
hubris_path = "drv/spartan7-loader/grapefruit"
builder = "buck2"
toolchain = "vivado"