:showtitle:
:toc: left
:numbered:
:icons: font
:revision: 1.0
:revdate: 2024-04-24

= eSPI Target Core

This block implements an eSPI target core. It is intended to provide SAFS (Slave attached Flash Storage)
boot functionality for an SP5-class AMD processor. It is intended to support single, dual and quad I/O Modes
at 66MHz which is the espi-spec maximum frequency. The actual internal fabric is intended to run at >3x the
SPI frequency so we shoot for 200MHz here.

== Overview
image::espi_block.drawio.svg[align="center"]

=== Link Layer

This block deals with the physical layer of the eSPI interface and contains the serializer/deserializer
and qspi I/O.  Sampled data is sent to the command processor (transaction layer) with a byte-wide streaming
interface via a CDC FIFO.  Responses from the response processor (transaction layer) are received via a 
byte-wide streaming interface (through CDC FIFO) and shipped out the serializer.

This is the only block expected to run in the faster clock domain.  To realize this, functionality,
we're leveraging the eSPI "WAIT_STATE" feature on every response, which allows us cycles to get from
the fast domain to the slow domain with the command packets, and have a couple of slow-domain cycles
to push responses back into the response FIFO before they are needed.

The number of wait states depends on the speed and bus-width of the eSPI interface.  We make decisions
in the slow domain based on the register settings and then propagate those decisions to the fast domain
as a wait-state count, using a simple cross-domain bus interface.
These wait states are inserted automatically at the link layer by the 
target, so the transaction layer doesn't need to worry about them.

The physical-layer will also insert 0xFFs if the FIFO is empty. This serves
2 purposes:
- It provides the ERROR response if the target chooses not to respond
- It raises the qspi lines to '1' at the final shift, which is needed by
the specification.

==== Turn around analysis

The cross-domain FIFOs take some cycles for data to propagate. Xilinx shows 1 wr-clk + 6 rd-clk cycles for data to propagate from one side to the other. Assuming the fast domain is at 200MHz and the slow domain is at 125MHz that results in a prop-delay of 5ns + 6*8ns = 53ns. The response
path will be slower since the read clock is faster but we can use this number as a rough estimate each way since we're trying to calculate how
many wait states we need to insert worst-case. Assigning 4 slow clocks to
do operational logic, we arrive at a turn-around time of 53ns * 2 + 32 ns = 138ns. Each WAIT_STATE will count as a byte-time, so this changes based
on the bus width and speed. Our worst-case here is quad mode, 66MHz so we have 2 clks/byte = 33ns/byte. We have 138ns / 33ns = 4.18 bytes rounding up to 5 waits.

We can do the same calculation for each of the speeds/modes resulting in this table:
5 wait states for quad mode, 66MHz
3 wait states for dual mode, 66MHz
2 wait states for single mode, 66MHz
4 wait states for quad mode, 50MHz
2 wait states for dual mode, 50MHz
1 wait state for single mode, 50MHz
3 wait states for quad mode, 33MHz
2 wait states for dual mode, 33MHz
1 wait state for single mode, 33MHz
2 wait states for quad mode, 25MHz
1 wait state for dual mode, 25MHz
1 wait state for single mode, 25MHz
2 wait states for quad mode, 20MHz
1 wait state for dual mode, 20MHz
1 wait state for single mode, 20MHz

The physical-layer inserts these wait states automatically before fetching
from the response FIFO as they are not counted in the CRC generation.


=== Debug Interface
We can enable a debug interface that muxes the streaming interfaces away from the serdes blocks and connects
them to FIFOs that are accessible via the AXI bus. This allows software to inject eSPI commands and capture
eSPI responses without needing an eSPI master connected in the system. With some minor modifications, this 
could also be used to log eSPI traffic when a real eSPI master is connected for debugging purposes.

=== Transaction Layer

At the transaction layer, the command processor is responsible for "parsing" the input stream and taking
action based on the command. The response processor is responsible for generating the response stream.

There are CRC blocks for the tx and rx paths. The CRC is calculated on the fly and is shipped out at the
appropriate time. Note that the eSPI master must *enable* CRC enforcement in the slave in order for this
block to actually enforce CRCs, otherwise it will accept any correctly formed packet.

=== Uart Channel
Use the posted peripheral interface to send and receive data on a uart channel. Right now we support a single
UART channel, but this could be expanded to support 2 channels using two different tags. We have a simplified
design here in that the data streams directly to a FIFO which may be undesirable if we are expecting CRC issues
in which case we'd need an additional buffer an only process data once the crc is verified.

=== Flash Channel
We implement the read commands of SAFS. We do not implement the write commands. The flash channel is a non-posted
block with 4 1024kB queue entries. It issues read requests to the eSPI flash block and then waits for the response,
once flash response data is enqueued it will alert the host that completed data is available and the host can
issue a non-posted GET to read the data.

== Simulation Environment
The simulation environment provides both a qspi master verification component
that wiggles the qspi lines like a spi master would, but can also leverage
the built-in debug interface to send arbitrary commands to the eSPI target
and get responses back at the byte-streaming layer. This logic can be utilized
for hardware-in-the-loop testing of the eSPI target core.

The "flash" block is a simple fake interface that behaves like our spi nor
controller with respect to reading so that we didn't have to build in a hard dependency
on that block here.

We do pull the FIFO'd UART in because it was simple to do so and then put the
UART in loopback mode so that tx => rx.

== Things not implemented
We don't adapt the response code and send data back after get_status currently. This would be 
a minor modification and efficiency improvement but is not strictly necessary for basic functionality.

=== Flash Write over eSPI interface
In our system our security model is such that we provide a read-only flash interface to the SP5 processor.
Any attempts to write the flash from the SP5 will be returned with a FATAL ERROR. This is a security feature
of our sleds, and not something we plan to support. The SP will be able to read/write flash and then will hand
off the flash to the SP5 and this espi interface.

=== UART interface
We provide a UART interface using the Peripheral channel and MESSAGE_WTIH_DATA cycle type for bidrectional
communication. The block alerts the host via the alert mechanism when data is available to be read. There 
are no thresholds or timeouts here so one or more bytes sitting in the FIFO causes an alert, but we 
always send the maximum available data (up to the max message size). We can evaluate adding
some thresholding if that would help efficiency we can add those if necessary.


