[libraries]
vunit_lib.files = [
  '.local/lib/python3.10/site-packages/vunit/vhdl/vunit_context.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/vunit_run_context.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/path/src/path.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/path/test/tb_path.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/verification_components/src/wishbone_slave.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/verification_components/src/signal_checker_pkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/verification_components/src/axi_read_slave.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/verification_components/src/avalon_sink.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/verification_components/src/axi_lite_master_pkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/verification_components/src/avalon_slave.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/verification_components/src/ram_master.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/verification_components/src/avalon_stream_pkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/verification_components/src/std_logic_checker.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/verification_components/src/axi_stream_protocol_checker.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/verification_components/src/axi_statistics_pkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/verification_components/src/sync_pkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/verification_components/src/uart_master.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/verification_components/src/bus_master_pkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/verification_components/src/stream_slave_pkg-body.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/verification_components/src/axi_stream_slave.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/verification_components/src/axi_slave_private_pkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/verification_components/src/axi_slave_pkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/verification_components/src/axi_stream_private_pkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/verification_components/src/stream_slave_pkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/verification_components/src/avalon_master.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/verification_components/src/memory_utils_pkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/verification_components/src/avalon_source.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/verification_components/src/vc_context.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/verification_components/src/avalon_pkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/verification_components/src/axi_pkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/verification_components/src/wishbone_master.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/verification_components/src/wishbone_pkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/verification_components/src/axi_stream_pkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/verification_components/src/memory_pkg-body.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/verification_components/src/bus_master_pkg-body.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/verification_components/src/sync_pkg-body.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/verification_components/src/axi_stream_master.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/verification_components/src/axi_write_slave.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/verification_components/src/uart_pkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/verification_components/src/axi_lite_master.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/verification_components/src/memory_pkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/verification_components/src/stream_master_pkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/verification_components/src/uart_slave.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/verification_components/src/axi_stream_monitor.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/verification_components/src/stream_master_pkg-body.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/verification_components/src/bus2memory.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/verification_components/test/tb_memory.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/verification_components/test/tb_memory_utils_pkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/verification_components/test/tb_avalon_slave.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/verification_components/test/tb_avalon_stream.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/verification_components/test/tb_avalon_stream_pkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/verification_components/test/tb_wishbone_slave.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/verification_components/test/tb_avalon_master.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/verification_components/test/tb_axi_stream.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/verification_components/test/tb_axi_write_slave.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/verification_components/test/tb_ram_master.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/verification_components/test/tb_avalon.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/verification_components/test/tb_axi_slave_private_pkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/verification_components/test/tb_axi_lite_master.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/verification_components/test/tb_uart.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/verification_components/test/tb_axi_read_slave.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/verification_components/test/tb_axi_statistics_pkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/verification_components/test/tb_sync_pkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/verification_components/test/tb_bus_master_pkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/verification_components/test/tb_std_logic_checker.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/verification_components/test/tb_axi_stream_protocol_checker.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/verification_components/test/tb_wishbone_master.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/core/src/stop_body_93-2002.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/core/src/stop_body_2008p.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/core/src/core_pkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/core/src/stop_pkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/com/src/com_support.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/com/src/com_common.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/com/src/com_deprecated.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/com/src/com_string.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/com/src/com_messenger.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/com/src/com_context.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/com/src/com_types.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/com/src/com.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/com/src/com_debug_codec_builder.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/com/src/com_api.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/com/test/tb_com_codec.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/com/test/tb_com.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/com/test/tb_com_msg_building.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/com/test/more_constants.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/com/test/custom_types.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/com/test/constants.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/run/src/run_deprecated_pkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/run/src/run_types.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/run/src/run_api.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/run/src/run.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/run/src/runner_pkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/run/test/tb_watchdog.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/run/test/tb_run.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/run/test/run_tests.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/check/src/check_api.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/check/src/check_deprecated_pkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/check/src/checker_pkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/check/src/check.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/check/src/checker_pkg-body.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/check/test/tb_check_equal_real.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/check/test/test_support.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/check/test/tb_checker.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/check/test/tb_check_failed.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/check/test/tb_check_stable.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/check/test/tb_check_passed.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/check/test/tb_check_implication.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/check/test/tb_check_sequence.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/check/test/tb_check_zero_one_hot.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/check/test/tb_result.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/check/test/tb_check_next.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/check/test/tb_check.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/check/test/tb_check_one_hot.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/check/test/tb_check_false.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/check/test/tb_check_relation_2008p.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/check/test/tb_check_not_unknown.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/check/test/tb_check_relation.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/osvvm/OsvvmContext.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/osvvm/ReportPkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/osvvm/MessagePkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/osvvm/NameStorePkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/osvvm/RandomProcedurePkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/osvvm/TranscriptPkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/osvvm/VendorCovApiPkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/osvvm/ScoreboardPkg_int.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/osvvm/ResolutionPkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/osvvm/MemoryPkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/osvvm/ScoreboardPkg_slv.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/osvvm/OsvvmGlobalPkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/osvvm/TbUtilPkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/osvvm/TextUtilPkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/osvvm/ScoreboardPkg_slv_c.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/osvvm/ScoreboardGenericPkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/osvvm/RandomPkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/osvvm/ResizePkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/osvvm/AlertLogPkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/osvvm/VendorCovApiPkg_Aldec.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/osvvm/SortListPkg_int.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/osvvm/ScoreboardPkg_int_c.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/osvvm/RandomBasePkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/osvvm/MessageListPkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/osvvm/CoveragePkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/osvvm/NamePkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/osvvm/demo/Demo_Rand.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/osvvm/demo/AlertLog_Demo_Global.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/osvvm/demo/AlertLog_Demo_Hierarchy.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/string_ops/src/string_ops.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/string_ops/test/tb_string_ops.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/random/src/random_pkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/random/test/tb_random_pkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/logging/src/location_pkg-body-2019p.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/logging/src/print_pkg-body.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/logging/src/print_pkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/logging/src/log_handler_pkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/logging/src/log_levels_pkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/logging/src/log_handler_pkg-body.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/logging/src/log_deprecated_pkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/logging/src/logger_pkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/logging/src/file_pkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/logging/src/ansi_pkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/logging/src/logger_pkg-body.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/logging/src/log_levels_pkg-body.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/logging/src/location_pkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/logging/test/tb_log.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/logging/test/tb_deprecated.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/logging/test/test_support_pkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/logging/test/tb_location.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/logging/test/tb_log_levels.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/data_types/src/data_types_private_pkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/data_types/src/integer_array_pkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/data_types/src/dict_pkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/data_types/src/codec_builder.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/data_types/src/queue_pkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/data_types/src/integer_vector_ptr_pool_pkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/data_types/src/byte_vector_ptr_pkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/data_types/src/codec.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/data_types/src/dict_pkg-2008p.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/data_types/src/integer_vector_ptr_pkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/data_types/src/types.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/data_types/src/codec-2008p.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/data_types/src/id_pkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/data_types/src/data_types_context.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/data_types/src/queue_pool_pkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/data_types/src/queue_pkg-2008p.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/data_types/src/event_pkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/data_types/src/integer_array_pkg-body.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/data_types/src/string_ptr_pool_pkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/data_types/src/codec_builder-2008p.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/data_types/src/queue_pkg-body.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/data_types/src/event_common_pkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/data_types/src/event_private_pkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/data_types/src/dict_pkg-body.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/data_types/src/api/external_integer_vector_pkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/data_types/src/api/external_string_pkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/data_types/test/tb_event_pkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/data_types/test/tb_string_ptr_pool.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/data_types/test/tb_codec.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/data_types/test/tb_byte_vector_ptr.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/data_types/test/tb_id.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/data_types/test/tb_event_private_pkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/data_types/test/tb_queue_pool.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/data_types/test/tb_integer_vector_ptr_pool.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/data_types/test/tb_queue.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/data_types/test/tb_codec-2008p.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/data_types/test/tb_integer_vector_ptr.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/data_types/test/tb_string_ptr.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/data_types/test/tb_integer_array.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/data_types/test/tb_dict-2008p.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/data_types/test/tb_queue-2008p.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/data_types/test/tb_dict.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/dictionary/src/dictionary.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/dictionary/test/tb_dictionary.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/array/src/array_pkg.vhd',
  '.local/lib/python3.10/site-packages/vunit/vhdl/array/test/tb_array.vhd',
]