load("//tools:hdl.bzl", "vhdl_unit", "vunit_sim")
load("//tools:rdl.bzl", "rdl_file")

rdl_file(
    name = "spi_nor_regs_rdl",
    src = "spi_nor_regs.rdl",
    outputs = [
        "spi_nor_regs_pkg.vhd", 
        "spi_nor_regs.html", 
        "spi_nor_regs.json",
    ],
    visibility = ["PUBLIC"],
)


# Just the reusable flash engine (command record, txn manager, link/clock
# gen) without the axil registers, RDL, XPM FIFOs, or eSPI plumbing, for
# standalone requesters like the Ethernet management block that own their
# own command sequencing.
vhdl_unit(
    name = "spi_nor_core",
    srcs = [
        "spi_nor_pkg.vhd",
        "link/spi_link.vhd",
        "link/spi_clk_gen.vhd",
        "spi_txn/spi_txn_mgr.vhd",
    ],
    standard = "2019",
    visibility = ["PUBLIC"],
)

vhdl_unit(
    name = "spi_nor_top",
    srcs = glob([
        "*.vhd",
        "link/*.vhd",
        "spi_txn/*.vhd",
        "espi_txn/*.vhd",
        "hash_txn/*.vhd",
    ]),
    standard = "2019",
    deps = [
        ":spi_nor_regs_rdl",
        "//hdl/ip/vhd/fifos:dcfifo_xpm",
        "//hdl/ip/vhd/axi_blocks:axilite_if_2k19",
        ],
    visibility = ["PUBLIC"],
)

vunit_sim(
    name = "spi_nor_top_sim",
    srcs = glob(["sims/*.vhd"]),
    deps = [
        ":spi_nor_top",
        "//hdl/ip/vhd/axi_blocks:axil_interconnect",
        "//hdl/ip/vhd/axi_blocks:axil8_resizer",
        "//hdl/ip/vhd/vunit_components:spi_nor_target_vc",
        ],
    visibility = ["PUBLIC"],
)