load("//tools:hdl.bzl", "vhdl_unit", "vunit_sim")

vhdl_unit(
    name = "spd_proxy_top",
    srcs = glob(["*.vhd"]),
    deps = [
        "//hdl/ip/vhd/common:tristate_if_pkg",
        "//hdl/ip/vhd/i2c/common:i2c_common_pkg",
        "//hdl/ip/vhd/i2c/common:i2c_glitch_filter",
        "//hdl/ip/vhd/i2c/controller:i2c_ctrl_txn_layer",
    ],
    standard = "2019",
    visibility = ['PUBLIC']
)
