load("//tools:hdl.bzl", "vhdl_unit", "vunit_sim")

vhdl_unit(
    name = "spd_proxy_top",
    srcs = glob(["*.vhd"]),
    deps = [
        "//hdl/ip/vhd/common:tristate_if_pkg",
        "//hdl/ip/vhd/i2c/common:i2c_common_pkg",
        "//hdl/ip/vhd/i2c/common:i2c_glitch_filter",
        "//hdl/ip/vhd/i2c/controller:i2c_ctrl_txn_layer",
    ],
    standard = "2019",
    visibility = ['PUBLIC']
)

vunit_sim(
    name = "spd_proxy_top_tb",
    srcs = glob(["sims/*.vhd"]),
    deps = [
        ":spd_proxy_top",
        "//hdl/ip/vhd/vunit_components:basic_stream",
        "//hdl/ip/vhd/vunit_components:i2c_cmd_vc",
        "//hdl/ip/vhd/vunit_components:i2c_target_vc",
        "//hdl/ip/vhd/vunit_components:i2c_controller_vc"
    ],
    visibility = ['PUBLIC'],
)