-- This Source Code Form is subject to the terms of the Mozilla Public
-- License, v. 2.0. If a copy of the MPL was not distributed with this
-- file, You can obtain one at https://mozilla.org/MPL/2.0/.
--
-- Black-box stub for the Vivado GTY transceiver wizard core (gtwizard_sgmii),
-- generated by xilinx_ip_gen/gtwizard_sgmii_ip.tcl. No synth, no sim; it only
-- makes the analyzer/LSP happy. Vivado binds this name to the generated IP.
--
-- The port list MUST match the generated core exactly (Vivado binds by name).
-- This mirrors the wizard output for the current tcl configuration: one channel
-- enabled (CHANNEL_ENABLE {X0Y10}, the SMA lane / quad 226 ch2) -> all
-- per-channel/per-common vectors are width 1 and userdata is 20 bits; QPLL0; raw
-- 20-bit datapath; in-core reset controller; EXTERNAL user clocking (the core
-- emits *outclk_out and takes *usrclk*_in + *_active_in, so sgmii_gt builds the
-- BUFG_GT clock network). If the generated core's ports differ, update to match.

library ieee;
    use ieee.std_logic_1164.all;

entity gtwizard_sgmii is
    port (
        gtwiz_userclk_tx_active_in         : in    std_logic_vector(0 downto 0);
        gtwiz_userclk_rx_active_in         : in    std_logic_vector(0 downto 0);
        gtwiz_reset_clk_freerun_in         : in    std_logic_vector(0 downto 0);
        gtwiz_reset_all_in                 : in    std_logic_vector(0 downto 0);
        gtwiz_reset_tx_pll_and_datapath_in : in    std_logic_vector(0 downto 0);
        gtwiz_reset_tx_datapath_in         : in    std_logic_vector(0 downto 0);
        gtwiz_reset_rx_pll_and_datapath_in : in    std_logic_vector(0 downto 0);
        gtwiz_reset_rx_datapath_in         : in    std_logic_vector(0 downto 0);
        gtwiz_reset_rx_cdr_stable_out      : out   std_logic_vector(0 downto 0);
        gtwiz_reset_tx_done_out            : out   std_logic_vector(0 downto 0);
        gtwiz_reset_rx_done_out            : out   std_logic_vector(0 downto 0);
        gtwiz_userdata_tx_in               : in    std_logic_vector(19 downto 0);
        gtwiz_userdata_rx_out              : out   std_logic_vector(19 downto 0);
        txdiffctrl_in                      : in    std_logic_vector(4 downto 0);
        txprecursor_in                     : in    std_logic_vector(4 downto 0);
        txpostcursor_in                    : in    std_logic_vector(4 downto 0);
        gtrefclk00_in                      : in    std_logic_vector(0 downto 0);
        qpll0outclk_out                    : out   std_logic_vector(0 downto 0);
        qpll0outrefclk_out                 : out   std_logic_vector(0 downto 0);
        gtyrxn_in                          : in    std_logic_vector(0 downto 0);
        gtyrxp_in                          : in    std_logic_vector(0 downto 0);
        rxbufreset_in                      : in    std_logic_vector(0 downto 0);
        rxcommadeten_in                    : in    std_logic_vector(0 downto 0);
        rxmcommaalignen_in                 : in    std_logic_vector(0 downto 0);
        rxpcommaalignen_in                 : in    std_logic_vector(0 downto 0);
        rxusrclk_in                        : in    std_logic_vector(0 downto 0);
        rxusrclk2_in                       : in    std_logic_vector(0 downto 0);
        txusrclk_in                        : in    std_logic_vector(0 downto 0);
        txusrclk2_in                       : in    std_logic_vector(0 downto 0);
        gtpowergood_out                    : out   std_logic_vector(0 downto 0);
        gtytxn_out                         : out   std_logic_vector(0 downto 0);
        gtytxp_out                         : out   std_logic_vector(0 downto 0);
        rxbufstatus_out                    : out   std_logic_vector(2 downto 0);
        rxbyteisaligned_out                : out   std_logic_vector(0 downto 0);
        rxbyterealign_out                  : out   std_logic_vector(0 downto 0);
        rxclkcorcnt_out                    : out   std_logic_vector(1 downto 0);
        rxcommadet_out                     : out   std_logic_vector(0 downto 0);
        rxoutclk_out                       : out   std_logic_vector(0 downto 0);
        rxpmaresetdone_out                 : out   std_logic_vector(0 downto 0);
        txoutclk_out                       : out   std_logic_vector(0 downto 0);
        txpmaresetdone_out                 : out   std_logic_vector(0 downto 0)
    );
end entity;
