-- This Source Code Form is subject to the terms of the Mozilla Public
-- License, v. 2.0. If a copy of the MPL was not distributed with this
-- file, You can obtain one at https://mozilla.org/MPL/2.0/.
--
-- Black-box stub for the Vivado GTY transceiver wizard core used on the SGMII
-- line side. No synth, no sim; it only makes the analyzer/LSP happy. Vivado
-- binds this name to the IP generated by xilinx_ip_gen/gtwizard_sgmii_ip.tcl.
--
-- The core is configured for a single GTY lane at 1.25 Gb/s with 8b10b BYPASSED
-- and a 10-bit raw user datapath, RX comma detect/align on K28.5, and an RX
-- buffer with clock correction so tx/rx share one 125 MHz user-clock domain.
--
-- NOTE: the exact port list of the generated core depends on the wizard
-- configuration and Vivado version. After generating the IP, reconcile this
-- stub (and gt/sgmii_gt.vhd) with the produced core's interface.

library ieee;
    use ieee.std_logic_1164.all;

entity gtwizard_sgmii is
    port (
        -- GT reference clock (single-ended, from the IBUFDS_GTE4 in sgmii_gt)
        gtrefclk00_in : in    std_logic;

        -- serial line side
        gtyrxp_in  : in    std_logic;
        gtyrxn_in  : in    std_logic;
        gtytxp_out : out   std_logic;
        gtytxn_out : out   std_logic;

        -- reset / status
        gtwiz_reset_clk_freerun_in : in    std_logic;
        gtwiz_reset_all_in         : in    std_logic;
        gtwiz_reset_tx_done_out    : out   std_logic;
        gtwiz_reset_rx_done_out    : out   std_logic;
        rxbyteisaligned_out        : out   std_logic;

        -- user clock (single domain for tx and rx), 125 MHz
        gtwiz_userclk_tx_usrclk2_out : out   std_logic;
        gtwiz_userclk_rx_usrclk2_out : out   std_logic;

        -- 10-bit raw code groups (8b10b bypassed)
        gtwiz_userdata_tx_in  : in    std_logic_vector(9 downto 0);
        gtwiz_userdata_rx_out : out   std_logic_vector(9 downto 0)
    );
end entity;
