-- This Source Code Form is subject to the terms of the Mozilla Public
-- License, v. 2.0. If a copy of the MPL was not distributed with this
-- file, You can obtain one at https://mozilla.org/MPL/2.0/.
--
-- Black-box stub for the Vivado clocking-wizard (MMCM) that derives the IDELAYCTRL
-- reference (200 MHz) from the GT refclk-derived free-running clock. No synth, no
-- sim; Vivado binds it to the IP generated by xilinx_ip_gen/idelay_pll_ip.tcl.

library ieee;
    use ieee.std_logic_1164.all;

entity idelay_pll is
    port (
        clk_in   : in    std_logic;   -- GT refclk-derived free-running clock
        clk_200m : out   std_logic;   -- IDELAYCTRL reference
        reset    : in    std_logic;
        locked   : out   std_logic
    );
end entity;
