-- This Source Code Form is subject to the terms of the Mozilla Public
-- License, v. 2.0. If a copy of the MPL was not distributed with this
-- file, You can obtain one at https://mozilla.org/MPL/2.0/.
--
-- Black-box stub for the Vivado clocking-wizard (MMCM) that doubles the 62.5 MHz
-- GT user clock to the 125 MHz PCS clock. Because the MMCM locks to the GT user
-- clock the two are phase-aligned (125 = 2 x 62.5), which is what lets the gear-
-- box cross between them without an asynchronous FIFO. No synth, no sim; Vivado
-- binds it to the IP generated by xilinx_ip_gen/usrclk_mmcm_ip.tcl.

library ieee;
    use ieee.std_logic_1164.all;

entity usrclk_mmcm is
    port (
        clk_in   : in    std_logic;   -- 62.5 MHz GT user clock
        clk_125m : out   std_logic;   -- 125 MHz PCS clock (phase-aligned)
        reset    : in    std_logic;
        locked   : out   std_logic
    );
end entity;
