-- This Source Code Form is subject to the terms of the Mozilla Public
-- License, v. 2.0. If a copy of the MPL was not distributed with this
-- file, You can obtain one at https://mozilla.org/MPL/2.0/.
--
-- Black-box stub for the Vivado VIO core (vio_polarity), generated by
-- xilinx_ip_gen/vio_polarity_ip.tcl. probe_out bits drive the GT serial polarity
-- inverts (controllable live over JTAG); probe_in bits mirror link/frame status
-- so the effect of a polarity flip is visible in the hardware manager without
-- arming the ILA. No synth, no sim; Vivado binds the name to the generated IP.

library ieee;
    use ieee.std_logic_1164.all;

entity vio_polarity is
    port (
        clk        : in    std_logic;
        probe_in0  : in    std_logic_vector(0 downto 0);    -- link_up
        probe_in1  : in    std_logic_vector(0 downto 0);    -- gt_ready
        probe_in2  : in    std_logic_vector(1 downto 0);    -- dbg_speed
        probe_in3  : in    std_logic_vector(15 downto 0);   -- dbg_txsop
        probe_in4  : in    std_logic_vector(15 downto 0);   -- dbg_rxsop
        probe_in5  : in    std_logic_vector(15 downto 0);   -- dbg_rxctl_frames
        probe_in6  : in    std_logic_vector(15 downto 0);   -- dbg_rgmii_frames
        probe_in7  : in    std_logic_vector(15 downto 0);   -- dbg_pcs_frames
        probe_out0 : out   std_logic_vector(0 downto 0);    -- invert_rx (init 1)
        probe_out1 : out   std_logic_vector(0 downto 0);    -- invert_tx (init 0)
        probe_out2 : out   std_logic_vector(4 downto 0);    -- tx_diffctrl   (init 0x18)
        probe_out3 : out   std_logic_vector(4 downto 0);    -- tx_precursor  (init 0)
        probe_out4 : out   std_logic_vector(4 downto 0)     -- tx_postcursor (init 0)
    );
end entity;
