name: vunit
run-name: ${{ github.actor }} is testing out GitHub Actions
on:
  [push]
jobs:
  Run-sim:
    runs-on: self-hosted
    steps:
        - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
        - name: Check out repository code
          uses: actions/checkout@v4
        - name: Update pip reqs
          run : python3 -m pip install --upgrade -r tools/requirements.txt
        