-- This Source Code Form is subject to the terms of the Mozilla Public
-- License, v. 2.0. If a copy of the MPL was not distributed with this
-- file, You can obtain one at https://mozilla.org/MPL/2.0/.

-- A no synth, no sim, black entity to make analysis happy.
-- Generated by xilinx_ip_gen/fmc_pll_ip.tcl (clk_wiz in phase-alignment
-- mode on the SP's FMC clock).

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use ieee.numeric_std_unsigned.all;

entity fmc_pll is
    port (
        clk_fmc_in : in std_logic;
        clk_fmc : out std_logic;
        clk_fmc_capture : out std_logic;
        reset : in std_logic;
        locked : out std_logic
);

end entity;
